### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by GabrieleCastellani**

### CODE REVIEW

**Review by woutervanranst — COMMENTED** [review]
Excellent job

**Review by hans-verbeeck — APPROVED** [review]
Great work!

**Comment by GabrieleCastellani** [comment]
#6

**Comment by GabrieleCastellani** [comment]
#5

**Review by woutervanranst — APPROVED** [review]
gdfgdfgdfgddgdgdgf

**Comment by frpascer443** [comment]
Good job

**Pull request merged**
